C:\Users\Julianna\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  


C:\ZST\HardDrives\src\model\RNN.py:2: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  from pandas import np


In [ ]:
def model_train_predict(model, train_loader,test_loader):
    ## Train
    criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor([1, 1]))
    # criterion = nn.NLLLoss()
    optimizer = optim.Adam(model.parameters())

    losses = {'train': [], 'test': []}
    for epoch_idx in range(120):
        train_loss = rnn_train_epoch(model, train_loader, optimizer, criterion)
        test_loss = evaluate(model, test_loader, criterion)
        losses['train'].append(train_loss)
        losses['test'].append(test_loss)
        # print(epoch_idx, train_loss, test_loss['loss'], test_loss['FAR'], test_loss['FDR'])
    
    return test_loss

In [2]:
import pandas as pd 
import numpy as np 
from datetime import datetime, timedelta
import random
from tqdm import tqdm
import os
from scipy.stats import bernoulli

import matplotlib.pyplot as plt

import torch
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader
from torch.nn.functional import softmax
from utils import FAR, FDR

%matplotlib inline

In [1]:
train_set = [[3, 0, 0, 1, 1, 2],
             [3, 0, 1, 2],
             [3, 0, 0, 0, 1, 1, 1, 2],
             [3, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2]]

In [3]:
len(train_set), len(train_set[0])

(4, 6)

In [8]:
for i, seq in enumerate(train_set):
    # print('seq:', seq)
    loss = 0
    for t in range(len(seq) - 1):
        x = torch.Tensor([seq[t]])
        y = torch.Tensor([seq[t +1]])
        # print('x:', x)
        # print('y:', y)

In [19]:
from model.RNN import RNN
model = RNN()
criterion = torch.nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)
train_set = [[3, 0, 0, 2, 1, 0],
             [3, 0, 1, 1, 2, 1],
             [3, 0, 1, 1, 2, 1],
             [3, 1, 1, 1, 1, 1]]

# 重复进行50次试验
num_epoch = 5
loss_list = []
for epoch in range(num_epoch):
    train_loss = 0
    # 对train_set中的数据进行随机洗牌，以保证每个epoch得到的训练顺序都不一样。
    np.random.shuffle(train_set)
    # 对train_set中的数据进行循环
    for i, seq in enumerate(train_set):
        loss = 0
        for t in range(len(seq) - 1):

            x = torch.Tensor([seq[t]])
            y = torch.Tensor([seq[ t +1]])
            # print(x)
            
            output, h_n = model(x)  # 综合加了RNN的模型输出 输出
            loss += criterion(output ,y.long())

        loss = 1.0 * loss / len(seq)  # 计算每字符的损失数值
        # print(loss)
        optimizer.zero_grad() # 梯度清空
        loss.backward()  # 反向传播
        optimizer.step()  # 一步梯度下降

tensor([3.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([3.])
tensor([0.])
tensor([0.])
tensor([2.])
tensor([1.])
tensor([3.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([3.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([0.])
tensor([0.])
tensor([2.])
tensor([1.])
tensor([3.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([3.])
tensor([0.])
tensor([0.])
tensor([2.])
tensor([1.])
tensor([3.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([3.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([0.])